// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEhy4sTKVsZnH0cganpArKvXiRb57mrPM',
    appId: '1:531336970501:android:78cdf1dd782239fd6ff76c',
    messagingSenderId: '531336970501',
    projectId: 'chat-app-b34c2',
    databaseURL: 'https://chat-app-b34c2-default-rtdb.firebaseio.com',
    storageBucket: 'chat-app-b34c2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVLJyIthW5hkxMwaofH6Gi8iIxX_luYnY',
    appId: '1:531336970501:ios:f2239d50a015f3f06ff76c',
    messagingSenderId: '531336970501',
    projectId: 'chat-app-b34c2',
    databaseURL: 'https://chat-app-b34c2-default-rtdb.firebaseio.com',
    storageBucket: 'chat-app-b34c2.appspot.com',
    iosClientId: '531336970501-qpmni3tfv2k510e943slol8brboqcn6m.apps.googleusercontent.com',
    iosBundleId: 'com.tgw.tgw',
  );
}
